version: '3'
services:
  app:
    container_name: app
    build: .
    ports:
      - 8000:8000
    tty: true
    volumes:
      - ./:/go/app
    networks:
      - GoDocker

networks:
  GoDocker:
    name: GoDocker
    external: true
